- hosts: nodes
  tasks:
    - name: "prepare source directory"
      file: path=source state=directory

    - name: "install git"
      yum: name=git state=present

    - name: "get source from github"
      git:  repo=git://github.com/scylladb/scylla dest=source/scylla version={{tag}} update=yes

    - name: "install devopment packages"
      yum: name={{item}} state=present
      with_items:
        - yaml-cpp-devel
        - lz4-devel
        - zlib-devel
        - snappy-devel
        - jsoncpp-devel
        - thrift-devel
        - antlr3-tool
        - antlr3-C++-devel
        - libasan
        - libubsan
        - gcc-c++
        - gnutls-devel
        - ninja-build
        - ragel
        - libaio-devel
        - cryptopp-devel
        - xfsprogs-devel
        - numactl-devel
        - hwloc-devel
        - libpciaccess-devel
        - libxml2-devel
        - python3-pyparsing

    - name: "submodules"
      shell: git submodule init && git submodule update --recursive
      args:
         chdir: source/scylla

    - name: "configure scylla"
      shell: ./configure.py --mode=release --with=scylla --disable-xen
      args:
         chdir: source/scylla

    - name: "build"
      shell: ninja-build build/release/scylla -j10
      args:
         chdir: source/scylla
